chore(vertical-nav): example config URLs don’t match any routes (#375)
The example doesn’t necessarily need to navigate anywhere, but should not generate the following error.

Error: Cannot match any routes. URL Segment: 'navigation/ipsum/intellegam/recteque'
Error: Cannot match any routes. URL Segment: 'navigation/adipscing'
…